### ISSUE TITLE
Issues with Signs and letters

### ISSUE THREAD

**Issue by moritz453** [kmierzeje/plantuml-powerpoint-addin#1]
Hi there,

I tried to figure this out myself but I could not. Maybe you can help me sort this out.
We use Plant UML a lot at work and I would like to have the diagrams important with the `include Diagramm` call in PlantUML. All that works just fine, which is a huge help for me.

However with certain Characters (such as ä, ü, ö and - most importantly - / ) we get issues with the decoding. So I was wondering if there is a way to fix this?

**Comment by kmierzeje** [comment]
Hi,

I need more details to reproduce the problem.
Please provide a code sample.

Kamil

**Comment by moritz453** [comment]
Well when you use the include Diagramm command and have any special characters you get the issue. As long as I type it in the plugin directly, i get no issues. 
I don't know how to share the details without breaking NDAs.

an example would be as simple as

@startuml
alice -> bob: Hellö
bob -> alice: /Yes
@enduml

Then you save the file on a server and call it with a CURL.

I tried to do something similar with a public server, since I cant share the actual links we are using in git. I know I get an error with this setup, but the characters are also messed up in the error message.
<img width="1414" alt="Screenshot 2022-02-17 at 14 54 39@2x" src="https://user-images.githubusercontent.com/71669090/154495978-16fbd4bf-e1d3-499d-a498-34ab576feaec.png">

**Comment by kmierzeje** [comment]
Hi,

I failed to reproduce problem with '/'. 
All the other characters are indeed decoded wrong. This is because plugin calls plantuml.jar with default charset, which is windows-1250 in my case.

It would be possible to fix by providing different charset to plantuml.jar, so plugin code needs to be updated.
I will keep the issue open, but cannot promise to fix it soon.

Kamil

**Comment by kmierzeje** [comment]
I updated the way how diagrams are rendered. Now utf8 is used always, so it should fix the problem
