### ISSUE TITLE
Dose it work in PowerPoint 2016?

### ISSUE THREAD

**Issue by rabbitq0082** [kmierzeje/plantuml-powerpoint-addin#2]
Hi, I am using PPT 2016, and I have installed the add-in (we could see it on below screenshot).
![image](https://user-images.githubusercontent.com/29980876/156306392-ca70c292-eea6-4b72-8108-ee2575065786.png)

But, the UML diagram not shown in PPT.
![image](https://user-images.githubusercontent.com/29980876/156305909-30cf1c12-a007-416c-9529-80be64bf37a9.png)

I am wandering if it is because of my PPT version(2016) not compatible with this add-in?
Thanks, looking forward to your reply.

**Comment by kmierzeje** [comment]
Hi,

Thanks for the info. I don't have access to PPT 2016, so cannot check myself. I can only assume that PPT 2016 does not support svg image format. There is some information in Microsoft's forums about problems with SVG in PPT 2016.

Currently my plugin uses only svg format, but it should not be difficult to add support for other formats.
I cannot promise it will happen soon.

Kamil

**Comment by rabbitq0082** [comment]
Got it, thanks still.
